// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/addresses/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addresses/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addresses/[id].put').default>>>>
    }
    '/api/addresses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addresses/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addresses/index.post').default>>>>
    }
    '/api/admin/stats': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats').default>>>>
    }
    '/api/admin/upload': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/upload').default>>>>
    }
    '/api/auth/forgot-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/forgot-password.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset-password.post').default>>>>
    }
    '/api/auth/validate': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/validate.get').default>>>>
    }
    '/api/cart/clear': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/clear.post').default>>>>
    }
    '/api/cart': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/index.get').default>>>>
    }
    '/api/cart/items/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/items/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/items/[id].put').default>>>>
    }
    '/api/cart/items': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cart/items/index.post').default>>>>
    }
    '/api/categories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].put').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.post').default>>>>
    }
    '/api/orders/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id].patch').default>>>>
    }
    '/api/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.post').default>>>>
    }
    '/api/payments/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/[id].get').default>>>>
    }
    '/api/payments/create-intent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/create-intent.post').default>>>>
    }
    '/api/products/:slug': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[slug].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[slug].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[slug].put').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.post').default>>>>
    }
    '/api/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/index.put').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].put').default>>>>
    }
    '/api/users/:id/toggle': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/toggle.post').default>>>>
    }
    '/api/users/change-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/change-password.post').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.post').default>>>>
    }
    '/api/users/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/me.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/me.put').default>>>>
    }
    '/api/wishlist/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/[id].delete').default>>>>
    }
    '/api/wishlist': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/index.get').default>>>>
    }
    '/api/wishlist/items/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/items/[id].delete').default>>>>
    }
    '/api/wishlist/items': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/items/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}