// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/22/2025, 4:30:57 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/plugins/**/*.{js,ts,mjs}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/stores/**/*.{js,ts,mjs}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/composables/**/*.{js,ts,mjs}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/utils/**/*.{js,ts,mjs}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/joaobatista/Documents/GitRepos/shopynuxt-starter-boilerplate/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;